### PR TITLE
mix: Added binding to Mix_OpenAudioDevice

### PR DESCRIPTION
**Pull request by exopulse**
Method Mix_OpenAudioDevice (unlike Mix_OpenAudio) allows device to be specified.

### CODE REVIEW

**Comment by veeableful** [comment]
Hi @exopulse, thank you for the binding! I believe the constants have already been defined in the `sdl` package or is there a reason that you added them?

**Comment by exopulse** [comment]
Hi @veeableful, I was just tying those more closely to the `mix` package. I can ditch those and stick to the `sdl` package constants if that is the preferred way.

**Comment by veeableful** [comment]
Hi @exopulse, are you perhaps not using the `sdl` package? I can see why you don't want to add another dependency if that is the case. Otherwise, I think they are not necessary (but definitely let me know if you have some use-case!).

**Comment by exopulse** [comment]
Hi @veeableful, you are right. I am using the `sdl` package and will remove these constants in favor of the existing ones. Thanks!

**Comment by veeableful** [comment]
I see. Thank you for making the change!

**Pull request merged**
