### PR TITLE
Align colors in SDL package to Go specification

### PR DESCRIPTION
**Pull request by mokiat**
Closes https://github.com/veandco/go-sdl2/issues/580

**This PR does the following changes:**
- It ensures that `Surface.Set` does not panic by handling colors correctly.
- It changes `Surface.At` to return `color.NRGBA` instead of `color.RGBA` which is the correct type for what is being returned (non-alpha-premultiplied color). This can be a breaking change if anyone ever expected a specific color from the method, despite the interface abstraction.
- It changes the `sdl.Color` type to `color.NRGBA` which is the correct representation of what is held in `sdl.Color` (non-alpha-premultiplied color). This is a breaking change. Preserving the `color.RGBA` type mapping would require more code rework.
- It fixes all of the color models to properly return 16bit-component alpha-premultiplied colors.
- It fixes a broken type reference in the `sdl` package

**Things to note:**
- The `color.RGBA` type in Go represents an alpha-premultiplied color and SDL2 appears to use standard non-alpha premultiplied colors everywhere. This is why `color.NRGBA` is the correct pick.
- The `Color.RGBA` method is expected to return 16bit (i.e. from 0x0000 to 0xFFFF) alpha-premultiplied color components.
- The PR makes heavy use of `color.NRGBA` and `color.NRGBAModel`, since these are the official ones and they have stable and optimized implementations for color conversions between alpha-premultiplied and non-alpha-premultiplied variants and from 8bit-component to 16bit-component colors.

**Side notes:**
- In the past I had written a [blog post](https://dev.to/mokiat/understanding-the-color-type-in-go-1k45) about Go's colors which can shed some light on the above considerations. Feel free to remove this section if such type of links are unacceptable here.
- While downscaling of bytes is trivial, upscaling is not so if you want to fill the whole scale. I have tried to come up with the proper bit-wise operation expressions but to double-check I have used the following Go program to empirically measure it: https://play.golang.com/p/fYrvt4TXFv2

### CODE REVIEW

**Comment by mokiat** [comment]
This PR should be ready for a more general public verification. The more people that have color scenarios in their apps to verify the better.

**Review by Lundis — APPROVED** [review]
Great job!

I ran into the same issue today. This PR solves all of my issues and does not seem to break anything. NRGBA should be correct indeed :+1:

**Comment by veeableful** [comment]
Thank you very much @mokiat! I will merge this into the `v0.4.x` branch and create a new patch release as well so more people can test it.

**Comment by veeableful** [comment]
Yes, `master` is preferred in most cases. I usually cherry-pick the commit into `v.4.x` branch afterwards. (Speaking of, I really should get `v0.5.x` out already 😓, just stuck on the static libraries currently).

**Pull request merged**
