### PR TITLE
Added SDL_CaptureMouse binding.

### PR DESCRIPTION
**Pull request by andreas-jonsson**
https://wiki.libsdl.org/SDL_CaptureMouse

---
This change is [Reviewable](https://reviewable.io/reviews/veandco/go-sdl2/207)

### CODE REVIEW

**Comment by veeableful** [comment]
Thanks for the patch! Merged.

**Comment by deadprogram** [comment]
This change appears to break Golang builds with the error `could not determine kind of name for C.SDL_CaptureMouse`

**Comment by andreas-jonsson** [comment]
Hmm... what build is that? It looks like it passes [CI](https://travis-ci.org/veandco/go-sdl2/builds/165142061).

(If there is a problem with it it should be reverted...)

What SDL version do you use?

**Comment by deadprogram** [comment]
How I noticed was that our own build started failing: https://travis-ci.org/hybridgroup/gobot/jobs/165784906#L753

This is how we're getting SDL for our builds: https://github.com/hybridgroup/gobot/blob/dev/.travis.yml#L17-L20

Thanks!

**Comment by andreas-jonsson** [comment]
I think your libsdl2 is to old. (Latest is 2.0.4)

Not sure what requirements the go-sdl2 authors have for the libsdl2 dependencies?

(Again if this is a problem we should revert the patch.)

You can apply [this](https://github.com/andreas-jonsson/openwar/blob/master/tools/sdl_from_source.sh) to your build process instead of apt-get them.

Exclude SDL2_mixer and the "--prefix=$SDL_PREFIX" part if you do not need them.

**Comment by veeableful** [comment]
I added a placeholder SDL_CaptureMouse() and prints a warning message if it's not supported by the native SDL2 library (should do that for other stubs as well..). Hopefully this solves the problem.

**Comment by deadprogram** [comment]
That fixed it for us. Thank you!

**Pull request merged**
