### PR TITLE
Improve channel handling

### PR DESCRIPTION
**Pull request by ZeroXLR**
Here are the code changes that were decoupled from the previous pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/veandco/go-sdl2/254)

### CODE REVIEW

**Comment by veeableful** [comment]
Hi @ZeroXLR, it seems to me that the code is functionally similar to the previous code and I also find the previous version easier to read. Is there a specific reason you want this to be merged in?

**Comment by ZeroXLR** [comment]
@veeableful To explain my two intentions:

- My first intention is straightforward: there is no need to make a new `done` channel in every `Do(..)` call; one should be enough to handle all of them.

- My second intention is unfortunately more vague: I was trying to keep `callQueue` uninitialized before `Main(..)`. My thinking was, we could use this fact to panic if `Do(..)` is called before `Main(..)`. Right now, doing things out of order causes an infinite loop which is not the best way to signal an error.

**Comment by veeableful** [comment]
I think with this approach, there might be an issue where the `done` signal the `Do()` function is waiting for comes from different `Do()` function if you run multiple of them in goroutines. But your second intention makes sense. I'm wondering if we should just panic by checking if the `callQueue` is `nil` in the `Do()` function.

**Comment by ZeroXLR** [comment]
Regarding `done`, does it matter if the signals are mismatched? As long as the each signal corresponds to each `f func()` sent to `callQueue`, there shouldn't be a problem. If the second `Do()` blocks for the `f` of the first `Do()`, then the first `Do()` will simply block for the `f` of the second `Do()`. At least that is my thinking on the matter.

Regarding the second issue, I am trying to get around checking for `nil` in every `Do()` call. After all, the checking only needs to happen once. I could declare an unexported `callInMain` function variable which `Do()` calls. This variable is initially set to a function that panics. However, inside `Main()`, I can initialize it to its real purpose. Do you want me to submit a new pull request with this change?

**Comment by veeableful** [comment]
@ZeroXLR, there might not be a problem but I think the code shouldn't lie. Unless it is proven to fix a problem or noticeably improve the performance, I'd say it's not worth changing a working function. I'm willing to change my mind if it is proven to be a worthwhile change, of course.

I'm having second thoughts about the `Do()` function actually. I think it's okay as it is since `Do()` are only needed when calling the SDL functions inside goroutines for which they can reference the examples, and like you say, it's a one-time thing. Plus they can read the comments you have written :)

**Pull request closed without merging**
