### PR TITLE
fix RWFromMem of sdl/audio_test.go

### PR DESCRIPTION
**Pull request by kjx98**
test: fix same BUG in sdl/audio_test.go RWFromMem with []byte param only

### CODE REVIEW

**Comment by kjx98** [comment]
add go test script to test sdl subsystem

**Comment by veeableful** [comment]
Hi @kjx98, thanks for your contributions! Could you separate the changes to different pull requests? Right now it has CI and test code changes which are not related.

Although, the reason we use SDL2 2.0.0 is because we want to make sure the binding is still usable on older version. I believe Xenial has SDL2 2.0.4. Other than that, I think any kind of improvement to the CI is welcome!

**Comment by kjx98** [comment]
Hi, @veeableful 
I've reversed CI patch, only test patch left.

**Comment by veeableful** [comment]
Sorry for getting back so late! I've merged your pull request. Thanks!

**Pull request merged**
