### PR TITLE
Don't use -mwindows flag when using static linking on Windows

### PR DESCRIPTION
**Pull request by Keithcat1**
The -mwindows flag tells GCC that we want the binary to be a GUI binary and have no command line termina, but there are two reasons it's a problem.
    First, normal MinGW ignores it, for example winlibs.com. LLVM-MinGW will properly apply this flag though.
    Second, it forces you to stop printing stuff to the console, and if you don't have a panic handler, it silently swallows the panic message and just exits with no indication of what went wrong. Also, Go has its own flag for making GUI binaries "go build --ldflags=-h WINDOWSGUI" has the same effect.

### CODE REVIEW

**Comment by veeableful** [comment]
Thanks @Keithcat1! Does this mean that users who want to statically compile on Windows should include `-ldflags=-h WINDOWSGUI` in the build command?

**Comment by Keithcat1** [comment]
Only if they're building a release version of their app that doesn't
need a terminal window.

**Comment by veeableful** [comment]
I see. I will merge this now and update README.md later with the new information!

**Comment by Keithcat1** [comment]
Small edit: It's -H windowsgui, not -h windowsgui.

**Comment by veeableful** [comment]
@Keithcat1 Ah! Thank you. I will correct it in the README.

**Pull request merged**
