### PR TITLE
sdl/sdl.go: trim code; improve godoc comments

### PR DESCRIPTION
**Pull request by ZeroXLR**
Simplified sdl/sdl.go code, especially the way the `callQueue` is managed; fixed godoc comments that were not rendering correctly

---
This change is [Reviewable](https://reviewable.io/reviews/veandco/go-sdl2/253)

### CODE REVIEW

**Comment by veeableful** [comment]
Hi @ZeroXLR, is it possible to separate the comments and code changes? Perhaps let us know what's the reason for changing the code as well. Thanks and sorry for the trouble!

**Comment by ZeroXLR** [comment]
@veeableful  My current computer is a backup with neither a github nor a golang installation. So the change you requested might take some time. Sorry.

**Comment by ZeroXLR** [comment]
Updated the pull request. Only comment changes were kept as requested. Now

- godoc renders code example about sdl.Main(..) correctly (it was missing indentations)

- users are warned about an infinite loop that happens if sdl.Do(..) is called without/before sdl.Main(..)

**Comment by veeableful** [comment]
Thanks @ZeroXLR. Looks good.

**Pull request merged**
