### PR TITLE
Updating static libraries to match version in build script (2.0.20)

### PR DESCRIPTION
**Pull request by dusk125**
I noticed that the scripts in [https://github.com/veandco/sdl2-static-library-build-scripts](sdl2-static-library-build-scripts) referenced version 2.0.20, but were built with 20.0.14, this PR updates the static libraries to 2.0.20

### CODE REVIEW

**Comment by veeableful** [comment]
Hi @dusk125, thanks for the PR! Currently the libraries generated by the scripts are really big compared to the original static libraries given by @gen2brain in `v0.4.x` which made me hesitant to update the static libraries. I think it's because each library contained its dependencies. If you have ways to improve that in the scripts, that would be a huge help! After that we can update the libraries in this PR again and I will merge it.

**Comment by gen2brain** [comment]
@veeableful I think I did `strip --strip-unneeded` for all libraries, but of course with `strip` for that platform.

**Comment by dusk125** [comment]
Thanks @gen2brain I can run that on this PR and see if that helps the filesize

**Comment by dusk125** [comment]
Ok I reran the build with strip commands in each of the common build scripts (I can add a PR to the scripts repo soon) and replaced the changed static libraries with the newer version

**Comment by veeableful** [comment]
Thanks @gen2brain and @dusk125. The file sizes are much smaller now!

**Pull request merged**
