### PR TITLE
Implement SDL_QueueAudio binding

### PR DESCRIPTION
**Pull request by MoonWatcher582**
Add support for the push model of SDL_AudioQueues.

---
This change is [Reviewable](https://reviewable.io/reviews/veandco/go-sdl2/215)

### CODE REVIEW

**Comment by veeableful** [comment]
Thanks!

**Comment by deadprogram** [comment]
This introduces a breaking change causing an error: `could not determine kind of name for C.SDL_QueueAudio` error. 

Similar to https://github.com/veandco/go-sdl2/pull/207 we need a placeholder for `SDL_QueueAudio`.

**Comment by veeableful** [comment]
@deadprogram Sorry about that. I added the placeholder function.

**Comment by deadprogram** [comment]
Thank you @veeableful

**Comment by deadprogram** [comment]
I see that commit, however, I now have the following error:

```
../../../github.com/veandco/go-sdl2/sdl/audio.go:7:9: note: #pragma message: SDL_QueueAudio is not supported before SDL 2.0.4
../../../github.com/veandco/go-sdl2/sdl/audio.go: In function 'SDL_QueueAudio':
../../../github.com/veandco/go-sdl2/sdl/audio.go:8:1: error: parameter name omitted
```

**Comment by veeableful** [comment]
Argh! Sorry, I should have tested it. It should work now.

**Comment by deadprogram** [comment]
Testing is what we're here for! :smile_cat: 

Working now, thanks for the quick fix.

**Pull request merged**
