### PR TITLE
Go implementation of the rect tools

### PR DESCRIPTION
**Pull request by velovix**
This is an implementation of the Rect methods and functions in Go. C is only necessary for Rect to interact with other parts of the library.

I kept the implementation mostly similar to the standard C implementation with a few tweaks to make it more Go-like. The only big change I made was to HasIntersection, which benchmarked better in this form than in the way they did it in C. This suggests more performance improvements could be made.

Tests are provided, but they might benefit from some more cases.

### CODE REVIEW

**Comment by jangler** [comment]
I agree that the tests could benefit from more cases. IMHO this code should get full test coverage, since it's an important part of the library and is more than a simple wrapper around C functions.

This brings the library one step closer to a native Go version, anyway, if there's ever a coordinated effort to go that route.

**Comment by krux02** [comment]
There will never be a native Go version of everything, because SDL itself is a wrapper around system functionality. Never the less, I really appreciate this path, because it removes calls to cgo when it isn't necessary.

**Comment by jangler** [comment]
Ah, I meant a standalone version (i.e. without non-system library dependencies), not a pure Go version (i.e. without cgo).

**Comment by jackyb** [comment]
Very cool, thanks!

**Pull request merged**
