### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flazz**
GetSurface doesn't return an err (anymore?)

### CODE REVIEW

**Comment by jackyb** [comment]
It returns a surface and an error.

**Comment by flazz** [comment]
i just `go get -v github.com/veandco/go-sdl2/sdl` and the source says different. did I get it wrong?

**Comment by jackyb** [comment]
Do you have it before? If so, you can update with `go get -u -v github.com/veandco/go-sdl2/sdl`. Otherwise, I'm not sure :/

**Comment by flazz** [comment]
strange i just got it about an hour ago

**Comment by flazz** [comment]
hey my apologies, I did have this from Nov 2014

**Pull request closed without merging**
